---

- include: install.yml
  when: ansible_selinux is defined and ansible_selinux.status == "enabled"
  tags: install

- include: config.yml
  when: ansible_selinux is defined and ansible_selinux.status == "enabled"
  tags: config

